DELETE http://localhost:3000/api/v1/loans/1/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJlZHdpbmpvaG5AZXhhbXBsZS5jb20iLCJyb2xlIjoic3VwZXJBZG1pbiIsImlhdCI6MTcyODUwMTE0MywiZXhwIjoxNzI4NTA0NzQzfQ.r0kjkTKy2XoImAP_ZGu0mG6OeswhXSjlGI0VJye6POc