GET http://localhost:3000/api/v1/loans
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJlZHdpbmpvaG5AZXhhbXBsZS5jb20iLCJyb2xlIjoic3VwZXJBZG1pbiIsImlhdCI6MTcyODQ5MTE1OCwiZXhwIjoxNzI4NDk0NzU4fQ.ihkxrYfNvogGDQJNql6IOLxOO4w-OjDfPtFHln9dhLM